os: osx
osx_image: xcode10.3
language: swift
xcode_project: DangerLab/DangerLab.xcodeproj # path to your xcodeproj folder
xcode_scheme: DangerLab
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone XÊ€
